account/urls.py
from django.urls import path
from .views import *

app_name = "account"

urlpatterns = [
    path('register/', signupuser_view, name='signupuser'),
    path('login/', signinuser_view, name="signinuser"),
    path("logout/", logoutuser_view, name="logout"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import about_view
from shop.context_processors import SearchResultsView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("shop.urls")),
    path('accounts/', include("account.urls")),
    path('about/', about_view, name="about"),
    path('search/', SearchResultsView.as_view(), name="search_result"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import *

app_name = "shop"

urlpatterns = [
    path('', homepage_view, name="homepage"),
    path('category/<slug:category_slug>/', homepage_view, name="product_by_category"),
    path('category/<slug:category_slug>/product/<slug:product_slug>/', detail_view, name="product_detail"),
    path("card/", card_detail, name="card_detail"),
    path("card/add/<int:product_id>", add_card, name="add_card"),
    path("card/remove/<int:product_id>", remove_card, name="remove_card"),
    path("card/delete/<int:product_id>", delete_card, name="delete_card"),
]

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="row justify-content-center my-3">
    <div class="col-5">
      <img src="{% static 'img/personal/image2.jpg' %}" class="img-fluid">
    </div>
  </div>

  <div class="row justify-content-center mb-3">
    <div class="col-md-9 text-center">
      <h1 id="hometext" class="font-weight-bold">Valeh Amirbekov</h1>
    </div>
  </div>

{% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/card.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ecommerce</title>
</head>

<body>    
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid mx-5 my-3">
          <a class="navbar-brand" href="{% url 'shop:homepage' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="70" height="50" fill="currentColor" class="bi bi-shop" viewBox="0 0 16 16">
                <path d="M2.97 1.35A1 1 0 0 1 3.73 1h8.54a1 1 0 0 1 .76.35l2.609 3.044A1.5 1.5 0 0 1 16 5.37v.255a2.375 2.375 0 0 1-4.25 1.458A2.371 2.371 0 0 1 9.875 8 2.37 2.37 0 0 1 8 7.083 2.37 2.37 0 0 1 6.125 8a2.37 2.37 0 0 1-1.875-.917A2.375 2.375 0 0 1 0 5.625V5.37a1.5 1.5 0 0 1 .361-.976l2.61-3.045zm1.78 4.275a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 1 0 2.75 0V5.37a.5.5 0 0 0-.12-.325L12.27 2H3.73L1.12 5.045A.5.5 0 0 0 1 5.37v.255a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0zM1.5 8.5A.5.5 0 0 1 2 9v6h1v-5a1 1 0 0 1 1-1h3a1 1 0 0 1 1 1v5h6V9a.5.5 0 0 1 1 0v6h.5a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1H1V9a.5.5 0 0 1 .5-.5zM4 15h3v-5H4v5zm5-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-3zm3 0h-2v3h2v-3z"/>
              </svg>Ecommerce
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown mx-5">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="30" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                      <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                      <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                    </svg>Welcome, {{ request.user.fullname }}
                  </a>
                  <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Profile</a></li>
                      <li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
                  </ul>
                </li> 
                {% else %}
                <li class="nav-item dropdown mx-5">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="20" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                            <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z"/>
                          </svg>Sign in
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'account:signinuser' %}">Sign in</a></li>
                        <li><a class="dropdown-item" href="{% url 'account:signupuser' %}">Sign up</a></li>
                    </ul>
                </li>
                {% endif %}
                {% if item_count > 0 %}
                <li class="nav-item mx-5">
                    <a class="nav-link" href="{% url 'shop:card_detail' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="20" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                          </svg>Basket({{item_count}})
                    </a>
                </li>
                {% else %}
                <li class="nav-item mx-5">
                  <a class="nav-link" href="{% url 'shop:card_detail' %}">
                      <svg xmlns="http://www.w3.org/2000/svg" width="40" height="20" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                          <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                        </svg>Basket
                  </a>
                </li>
                {% endif %}
                <li class="nav-item dropdown mx-5">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Category
                    </a>
                    <ul class="dropdown-menu">
                        {% for categ in categories_links %}
                          <li><a class="dropdown-item" href="{{ categ.get_url }}"> {{ categ.title }} </a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item mx-5">
                  <a class="nav-link" href="{% url 'about' %}">
                      About
                  </a>
                </li>
            </ul>
            <form class="d-flex" role="search" action="{% url 'search_result' %}" method="get">
              <input name="q" class="form-control me-2" type="text" placeholder="Search..." aria-label="Search">
              <button class="btn btn-outline-primary" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      {% block body %}{% endblock body %}

      <footer class="bg-dark text-white mt-5 p-5">
        <div class="container">
          <p class="lead text-center">Copyright &copy; 2022 Ecommerce</p>
        </div>
      </footer>
</body>

<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

templates/card.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Card
{% endblock title %}
    
{% block body %}

    {% if not card_items %}
    <div class="text-center">
        <br>
        <h1 class="text-center product_title">
            Your Card Is Empty
        </h1>
        <br>
        <p class="text-center">
            Click <a href="{% url 'shop:homepage' %}">here</a> to go back to products
        </p>
    </div>
    {% else %}
    <div class="text-center">
        <br>
        <div class="text-center product_title">
            Shopping Card
        </div>
    </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table">
                <thead>
                    <tr>
                        <th colspan="4">
                            Your Items
                        </th>
                </thead>
                {% for card_item in card_items %}
                <tr>
                    <td>
                        <a href="{{ card_item.product.get_absolute_url }}">
                            <img src="{{ card_item.product.image.url }}"
                            alt="" height ="100" width = "100">
                        </a>
                    </td>
                    <td class="text-left">
                        {{ card_item.product.name }}
                        <br>
                        SKU: {{ card_item.product.id }}
                        <br>
                        Unit Price: {{ card_item.product.product_max_price }}$
                        <br>
                        Quantity: {{ card_item.quantity }} x {{ card_item.product.product_max_price }}$
                    </td>
                    <td>
                        {{ card_item.sub_total }}$
                    </td>
                    <td>
                        {% if card_item.quantity < card_item.product.is_active %}
                        <a href="{% url 'shop:add_card' card_item.product.id %}" style="text-decoration: 0">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus card-icons" viewBox="0 0 16 16">
                                <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9V5.5z"/>
                                <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                            </svg>
                        </a>
                        <a href="{% url 'shop:remove_card' card_item.product.id %}" style="text-decoration: 0">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-circle card-icons" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                <path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z"/>
                            </svg>
                        </a>
                        <a href="{% url 'shop:delete_card' card_item.product.id %}" style="text-decoration: 0">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill card-icons" viewBox="0 0 16 16">
                                <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                            </svg>
                        </a>
                        {% else %}
                        <a href="{% url 'shop:remove_card' card_item.product.id %}" style="text-decoration: 0">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-circle card-icons" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                <path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z"/>
                            </svg>
                        </a>
                        <a href="{% url 'shop:delete_card' card_item.product.id %}" style="text-decoration: 0">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill card-icons" viewBox="0 0 16 16">
                                <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                            </svg>
                        </a>
                        {% endif %}
                    </td>
                </tr>
                
                {% endfor %}
            </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table card-table">
                <thead class="card-thead">
                    <tr>
                        <th colspan="4">
                            Check Out
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            Please chech your card before payment
                        </td>
                    </tr>
                    <tr class="text-left">
                        <td>
                            Your total bill is: <strong>${{ total }}</strong>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'shop:homepage' %}" style="text-decoration: 0">
                    <button type="button" class="btn btn-lg btn-block bg-dark text-white">
                        Back To Products
                    </button>
                </a>
            </div>
        </div>
    </div>
    {% endif %}

{% endblock body %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}

    Product

{% endblock title %}

{% block body %}

<div class="container py-5">
    <div class="row mt-5">
        <div class="col-10 mx-auto col-md-6 my-3">
            <img class="col-10 mx-auto col-md-6 my-3" src="{{ product.image.url }}">
        </div>
    </div>
</div>
<div class="col-10 mx-auto col-md-6 my-3">
    <div>
        <h1 class="product_title">{{ product.name }}</h1>
        <h5 class="text-info font-italic mb-4">
            ${{product.product_max_price}}
        </h5>
        <p class="product_desc">Product Description</p>
        <p class="text-justify product_text">
            {{ product.descriptions }}
        </p>
        {% if user.is_authenticated %}
            {% if product.is_active <= 0 %}
            <p class="text-justify product_text">Out of Stock</p>
            {% else %}
            <a href="{% url 'shop:add_card' product.id %}">Add To Card</a>
            {% endif %}
        {% else %}
            {% if product.is_active <= 0 %}
            <p class="text-justify product_text">Out of Stock</p>
            {% else %}
            <a href="{% url 'account:signinuser'%}">Add To Card</a>
            {% endif %}
        {% endif %}
        
    </div>
</div>

{% endblock body %}

templates/homepage.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="container-fluid">
    <div class="row">
        <img class="img-fluid" src="{% static 'img/pages/1.jpg' %}">
    </div>
</div>

<div class="py-4">
    <div class="container">
        <div class="row">
            <div class="col-10 mx-auto my-2 text-center">
                <h1 class="text-capitalize font-weight-bold">
                    Our Products
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        {% for product in products %}
            <div class="col-9 mx-auto col-md-6 col-lg-3">
                <div class="card mb-4">
                    <div class="p-4">
                        <a href="{{ product.get_url }}">
                            <img class="card-img-top" src="{{ product.image.url }}"
                            alt="{{ product.name }}">
                        </a>
                    </div>
                    <div class="card-footer d-flex justify-content-between"
                    style="background : transparent; border-color : transparent;">
                        <p class="font-weight-bold mb-0">
                            {{ product.name }}
                        </p>
                        <h5 class="text-info font-italic mb-0">
                            ${{ product.product_max_price }}
                        </h5>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock body %}

templates/search_result.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="py-4">
    <div class="container">
        <div class="row">
            <div class="col-10 mx-auto my-2 text-center">
                <h1 class="text-capitalize font-weight-bold">
                    Search Results
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        {% for product in object_list %}
            <div class="col-9 mx-auto col-md-6 col-lg-3">
                <div class="card mb-4">
                    <div class="p-4">
                        <a href="{{ product.get_url }}">
                            <img class="card-img-top" src="{{ product.image.url }}"
                            alt="{{ product.name }}">
                        </a>
                    </div>
                    <div class="card-footer d-flex justify-content-between"
                    style="background : transparent; border-color : transparent;">
                        <p class="font-weight-bold mb-0">
                            {{ product.name }}
                        </p>
                        <h5 class="text-info font-italic mb-0">
                            ${{ product.product_max_price }}
                        </h5>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock body %}

templates/signinuser.html
{% extends 'base.html' %}
{% block body %}

<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <h2>Login</h2>
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="username" class="form-control" id="username">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" class="form-control" id="password">
            </div>
                <button type="submit" class="btn btn-primary">Login</button>
        </form>
        <hr>
        <div class="text-center">
            Need an account? <a href="{% url 'account:signupuser' %}">Sign Up here</a>
        </div>
    </div>
</div>

{% endblock body %}

templates/signupuser.html
{% extends 'base.html' %}
{% block body %}

<body>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Sign Up</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="fullname">Full Name</label>
                    <input type="text" name="fullname" class="form-control" id="fullname">
                </div>
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" class="form-control" id="password">
                </div>
                <div class="form-group">
                    <label for="confirm">Confirm Password</label>
                    <input type="password" name="confirm" class="form-control" id="confirm">
                </div>
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </form>
            <hr>
            <div class="text-center">
                Do you already have an account? <a href="{% url 'account:signinuser' %}">Login here</a>
            </div>
        </div>
    </div>        
</body>

{% endblock body %}